import { reactive } from "vue";
// 本地项目url地址
export const baseURL = "/";

export const options = reactive({
  availableJobs: [
    {
      value: "Internet",
      label: "互联网",
      children: [
        {
          value: "Back-end development",
          label: "后端开发",
          children: [
            { value: "Java", label: "Java 开发工程师" },
            { value: "C/C++", label: "C/C++ 开发工程师" },
            { value: "PHP", label: "PHP 开发工程师" },
            { value: "Python", label: "Python 开发工程师" },
            { value: "C#", label: "C# 开发工程师" },
            { value: "Golang", label: "Golang 开发工程师" },
            { value: "Node.js", label: "Node.js 开发工程师" },
            { value: "Hadoop", label: "Hadoop 工程师" },
            { value: "Blockchain engineer", label: "区块链工程师" },
            { value: "Full-stack engineer", label: "全栈工程师" },
            { value: "Other", label: "其他" },
          ],
        },
        {
          value: "Front-end & Mobile development",
          label: "前端/移动开发",
          children: [
            { value: "Front-end dev", label: "前端开发工程师" },
            { value: "Android", label: "Android 开发工程师" },
            { value: "iOS", label: "iOS 开发工程师" },
            { value: "U3D", label: "Unity 3D 开发工程师" },
            { value: "UE4", label: "Unreal Engine 4 开发工程师" },
            { value: "JavaScript", label: "JavaScript 开发工程师" },
            { value: "Other", label: "其他" },
          ],
        },
        {
          value: "Testing",
          label: "测试",
          children: [
            { value: "Test engineer", label: "测试工程师" },
            { value: "Software testing", label: "软件测试工程师" },
            { value: "Automation testing", label: "自动化测试工程师" },
            { value: "Functional testing", label: "功能测试工程师" },
            { value: "Test development", label: "测试开发工程师" },
            { value: "Hardware testing", label: "硬件测试工程师" },
            { value: "Game testing", label: "游戏测试工程师" },
            { value: "Performance testing", label: "性能测试工程师" },
            { value: "Penetration testing", label: "渗透测试工程师" },
            { value: "Other", label: "其他" },
          ],
        },
        {
          value: "Operations & Technical Support",
          label: "运维/技术支持",
          children: [
            { value: "Ops engineer", label: "运维工程师" },
            { value: "Network engineer", label: "网络工程师" },
            { value: "Cybersecurity", label: "网络安全工程师" },
            { value: "System engineer", label: "系统工程师" },
            { value: "DevOps engineer", label: "运维开发工程师" },
            { value: "System administrator", label: "系统管理员" },
            { value: "DBA", label: "数据库管理员(DBA)" },
            { value: "System security", label: "系统安全工程师" },
            { value: "Technical documentation", label: "技术文档工程师" },
            { value: "Other", label: "其他" },
          ],
        },
        {
          value: "Sales Technical Support",
          label: "销售技术支持",
          children: [
            { value: "Pre-sales support", label: "售前技术支持" },
            { value: "Post-sales support", label: "售后技术支持" },
            { value: "Sales technical support", label: "销售技术支持工程师" },
            { value: "Other", label: "其他" },
          ],
        },
      ],
    },
    {
      value: "AI/Data",
      label: "AI/数据",
      children: [
        {
          value: "Artificial Intelligence",
          label: "人工智能",
          children: [
            { value: "Image Algorithm", label: "图像算法" },
            { value: "Natural Language Processing", label: "自然语言处理算法" },
            { value: "Big Model Algorithm", label: "大模型算法" },
            { value: "Data Mining", label: "数据挖掘" },
            { value: "SLAM Algorithm", label: "SLAM算法" },
            { value: "Recommendation Algorithm", label: "推荐算法" },
            { value: "Search Algorithm", label: "搜索算法" },
            { value: "Voice Algorithm", label: "语音算法" },
            {
              value: "Autonomous Driving System Engineer",
              label: "自动驾驶系统工程师",
            },
            { value: "Other", label: "其他" },
          ],
        },
        {
          value: "Data",
          label: "数据",
          children: [
            { value: "Data Analyst", label: "数据分析师" },
            { value: "Data Development", label: "数据开发" },
            { value: "Data Warehouse", label: "数据仓库" },
            { value: "Data Mining", label: "数据挖掘" },
            { value: "Data Architect", label: "数据架构师" },
            { value: "Other", label: "其他" },
          ],
        },
      ],
    },
    {
      value: "Electronics",
      label: "电子",
      children: [
        {
          value: "Electronics/Hardware Development",
          label: "电子/硬件开发",
          children: [
            { value: "Electronics Engineer", label: "电子工程师" },
            { value: "Hardware Engineer", label: "硬件工程师" },
            { value: "Embedded Software Engineer", label: "嵌入式软件工程师" },
            { value: "FPGA Development", label: "FPGA开发" },
            { value: "MCU", label: "单片机" },
            { value: "Driver Development Engineer", label: "驱动开发工程师" },
            { value: "PCB Engineer", label: "PCB工程师" },
            {
              value: "Electronic Maintenance Technician",
              label: "电子维修技术员",
            },
            { value: "RF Engineer", label: "射频工程师" },
            { value: "Circuit Design", label: "电路设计" },
            { value: "System Integration", label: "系统集成" },
            { value: "Optical Engineer", label: "光学工程师" },
            { value: "DSP Development", label: "DSP开发" },
            { value: "ARM Development", label: "ARM开发" },
            { value: "Other", label: "其他" },
          ],
        },
        {
          value: "Semiconductor/Chip",
          label: "半导体/芯片",
          children: [
            { value: "Integrated Circuit IC Design", label: "集成电路IC设计" },
            {
              value: "Digital IC Verification Engineer",
              label: "数字IC验证工程师",
            },
            {
              value: "Analog Layout Design Engineer",
              label: "模拟版图设计工程师",
            },
            { value: "Chip Test Engineer", label: "芯片测试工程师" },
            { value: "DFT Engineer", label: "DFT工程师" },
            { value: "FAE", label: "FAE" },
            { value: "Digital Frontend Designer", label: "数字前端设计师" },
            { value: "Digital Backend Engineer", label: "数字后端工程师" },
            { value: "Analog IC Design Engineer", label: "模拟IC设计工程师" },
            { value: "Other", label: "其他" },
          ],
        },
      ],
    },
    {
      value: "Electrical",
      label: "电气",
      children: [
        {
          value: "Electrical/Automation",
          label: "电气/自动化",
          children: [
            { value: "Electrical Engineer", label: "电气工程师" },
            { value: "Electrical Design Engineer", label: "电气设计工程师" },
            { value: "Automation", label: "自动化" },
            { value: "Mechatronics Engineer", label: "机电工程师" },
            {
              value: "Building Electromechanical Engineer",
              label: "建筑机电工程师",
            },
            { value: "Other", label: "其他" },
          ],
        },
      ],
    },
    {
      value: "Telecommunications",
      label: "通信",
      children: [
        {
          value: "Electrical/Automation",
          label: "通信",
          children: [
            { value: "Telecom Specialist", label: "通信项目专员" },
            { value: "Telecom Project Manager", label: "通信项目经理" },
            { value: "Telecom Technology Engineer", label: "通信技术工程师" },
            { value: "Telecom R&D Engineer", label: "通信研发工程师" },
            {
              value: "Wireless/Radio Frequency Engineer",
              label: "无线/射频通信工程师",
            },
            { value: "Mobile Communication Engineer", label: "移动通信工程师" },
            { value: "Telecom Network Engineer", label: "电信网络工程师" },
            { value: "Data Communication Engineer", label: "数据通信工程师" },
            {
              value: "Telecommunication Test Engineer",
              label: "通信测试工程师",
            },
            { value: "Optical Communication Engineer", label: "光通信工程师" },
            { value: "Optical Transmission Engineer", label: "光传输工程师" },
            { value: "Optical Network Engineer", label: "光网络工程师" },
            { value: "Telecom Power Supply Engineer", label: "通信电源工程师" },
            { value: "Wired Transmission Engineer", label: "有线传输工程师" },
            { value: "Telecom Equipment Engineer", label: "通信设备工程师" },
            { value: "Core Network Engineer", label: "核心网工程师" },
            {
              value: "Telecommunication Standardization Engineer",
              label: "通信标准化工程师",
            },
            { value: "Other", label: "其他" },
          ],
        },
      ],
    },
  ],
  allWorks: [
    {
      title: "资深Java开发工程师",
      salary: "30-60K·16薪",
      education: "大专",
      skill: [
        "MyBatis",
        "NoSQL",
        "zookeeper",
        "Java",
        "Netty",
        "MongoDB",
        "SpringBoot",
        "数据结构",
        "Redis",
        "Dubbo",
        "SQL",
        "Kafka",
        "rocketmq",
        "IO",
        "RabbitMQ",
        "springcloud",
        "网络",
        "JVM",
      ],
      info: "交通补助，年终奖，五险一金，员工旅游，零食下午茶，餐补，带薪年假，节日福利，通讯补贴",
      kind1: "互联网",
      kind2: "后端开发",
      kind3: "Java",
      description:
        "职位要求：1.专科及以上学历，计算机相关专业，3-8年工作经验；2.Java基础扎实，精通多线程、并发、集合、网络、io等基础知识，熟悉JVM；3.熟练掌握各类算法、常用数据结构、设计模式和DDD领域建模；4.精通Apache DolphinScheduler等大数据分布式调度引擎；5.深入理解SpringBoot、SpringCloud、Dubbo、Netty、MyBatis、Sentinel、Nacos、Apollo等开源框架或产品（至少满足2项）的机制与代码；6.熟悉SQL、NoSQL、缓存、消息通信、队列、异步框架等技术；7.熟悉高性能、高并发系统设计方案，如分布式缓存、消息队列等；8.对典型的分布式场景有设计经验，掌握分布式键、分布式锁、分布式事务等关键技术，并能熟练应用；9.熟悉各类中间件（至少满足2项），如ZooKeeper、Redis、InfluxDB、MongoDB、RabbitMQ、Kafka、RocketMQ等；10.思路清晰，具有优秀的分析与沟通能力，编码规范。",
      province: "上海市",
      city: "市辖区",
      district: "杨浦区",
      address: "上海杨浦区互联宝地c2",
      major: ["计算机"],
      neo4j: 626,
      company: "上海识装信息科技有限公司",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "Android",
      salary: "6-12K",
      education: "本科",
      skill: [
        "Java",
        "ui",
        "app",
        "多线程",
        "Android",
        "android ndk",
        "Android Studio",
        "网络",
      ],
      info: "带薪年假，节日福利，餐补，年终奖，工龄奖，绩效奖金",
      kind1: "互联网",
      kind2: "前端/移动开发",
      kind3: "移动开发",
      description:
        "岗位职责：\n1、 从事安卓APP移动平台客户端软件的功能设计、开发和实现；\n2、 根据产品功能模块设计，编码实现各模块功能，并确保开发质量与进度；\n3、 对于产品的BUG进行问题的修正；\n4、 对移动端应用做出系统优化和数据优化；\n5、 产品的迭代和维护；\n岗位要求：\n1、熟练掌握Java, 熟悉面向对象思想，熟悉常用设计模式，编程习惯良好；\n2、熟练掌握安卓应用开发技术（包括UI、网络、存储、多线程等方面）、开发工具和测试工具；\n3、熟练掌握Android开发平台及框架原理，精通系统组件的使用，能进行自定义控件的封装；\n4、熟悉android屏幕适配，有APP性能优化的经验；\n5、有独立完整开发 App 经验优先，有个人上架 App 优先；\n6、良好的沟通及人际技巧，与团队成员高效协作；\n7.熟悉安卓各大市场APP上线流程",
      province: "安徽省",
      city: "合肥市",
      district: "瑶海区",
      address: "合肥合肥市瑶海区都市科技工业园C6栋101",
      major: [],
      neo4j: 8852,
      company: "统旭智慧科技",
      logo: "https://img.bosszhipin.com/beijin/upload/com/logo/20220926/7b5b554d84f9729c157fc655c4aecc0c8cf8e49fb37c6801ccd75b28d7f169b2a9c7a6bce39fbdca.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "小程序开发工程师",
      salary: "2-3K",
      education: "大专",
      skill: ["CSS", "Javascript", "HTML", "web", "小程序", "vuejs", "uni-app"],
      info: "全勤奖，五险一金，通讯补贴，带薪年假，生日福利，加班补助，年终奖，节日福利",
      kind1: "互联网",
      kind2: "前端/移动开发",
      kind3: "移动开发",
      description:
        "只要实习生，只要实习生，只要实习生！1、与后台工程师、设计师密切合作，参与前端产品的方案设计;2、参与公司项目设计、项目测试以及后期迭代的整个周期当中。任职要求:1、熟练掌握HTML、css、JavaScript;1到3年左右前端工作经验;2、熟悉Bootstr、Vuejs框架、uni-app前端应用框架;3、至少参与过一个完整Web项目开发。加分条件:1.熟悉uni-app框架;2.参与开发过微信小程序或者微信公众号的开发:3.有自己的作品展示。",
      province: "云南省",
      city: "曲靖市",
      district: "麒麟区",
      address: "曲靖麒麟区闽南建材城3区466号",
      major: [],
      neo4j: 6749,
      company: "上海酷柒网络技术有限公司",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "软件实施工程师",
      salary: "4-6K",
      education: "大专",
      skill: ["SaaS"],
      info: null,
      kind1: "互联网",
      kind2: "后端开发",
      kind3: "后端其他开发",
      description:
        "公司招聘：1、人事行政专员1名                    2、售后人员1名                    3、软件实施工程师2名薪资均4—6k，具体可以面谈需要相关工作经验至少半年企业介绍：四川仲医达医疗科技有限公司成立于2022年1月，是一家专业的SAAS服务供应商，股东背景为上市企业四川合纵药易购，公司强有力的上游供应链资源和阿里AI智能明星团队，将把基层医疗机构搭建为生态大平台。想要加入我们的小伙伴，快快联系吧。公司法定假日+五险一金+周末双休加分项有以下行业经验：医疗健康·计算机软件·计算机服务",
      province: "四川省",
      city: "成都市",
      district: "金牛区",
      address: "成都金牛区成都健康智谷7号楼15楼",
      major: ["计算机"],
      neo4j: 1045,
      company: "四川仲医达医疗科技有限公司",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "初级前端",
      salary: "2-3K",
      education: "大专",
      skill: ["GIT", "vue3", "Javascript", "web", "vue2", "HTML5", "vue"],
      info: "定期体检，通讯补贴，员工旅游，年假递增，餐补，补充医疗保险，节日福利，带薪年假，五险一金，加班补助，年终奖，股票期权",
      kind1: "互联网",
      kind2: "前端/移动开发",
      kind3: "前端开发工程师",
      description:
        "工作职责：1.根据项目要求，原型设计要求，完成系统前端开发工作；2.负责Web平台的前端技术框架研究和开发3.按照公司规范开发，保证交付代码质量，持续改进重构；4.配合产品、完成项目迭代，不断优化和提升用户体验5.深入分析和解决前端遇到的各种技术、性能、跨终端兼容问题6. 负责实现产品前端页面设计、开发，并整合前端与服务端代码任职要求：1.专科以上学历，只收24届应届生。最少时间 一年，固定1周至少5天可上岗，有项目经验请提供项目2.熟悉使用Javascript、Html5、CSS3、vue等前端开发技术栈。会Vue2/Vue3 ，熟悉git 的应届生优先考虑3.拥有良好的代码习惯，要求结构清晰，命名规范，逻辑性强，代码冗余率低4.具有快速学习和解决问题的能力。                                                            5.上班时间 朝九晚六，等福利，地铁口附近6.具备今日事今日毕的良好习惯",
      province: "福建省",
      city: "厦门市",
      district: "思明区",
      address: "厦门思明区观音山国际商务营运中心6号楼1",
      major: [],
      neo4j: 4244,
      company: "易视线（厦门）科技有限公司",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "网络安全工程师",
      salary: "8-12K·16薪",
      education: "大专",
      skill: ["华为", "ITIL"],
      info: "带薪年假，五险",
      kind1: "互联网",
      kind2: "运维/技术支持",
      kind3: "网络安全",
      description:
        "工作职责：1.完成客户网站、业务系统的等保安全评估工作；2.对客户各类信息化系统进行安全加固；3.对客户安全事件及时响应，清理后门，根据日志分析攻击途径；4.跟踪最近安全漏洞信息，进行安全技术研究，包括安全防范技术，黑客技术等；5.定期为客户交付安全类评估与漏扫报告；6.负责为客户及团队开展信息安全技术与管理领域相关培训；任职要求：1.计算机、网络空间安全或相关专业专科及以上学历；2.具有1年以上相关工作经历；3. 熟悉华为网络设备技术；4. 熟悉客户网络系统与防火墙、具备故障分析诊断、系统应急处理、网络优化及建议等二线技术支持能力。5.具有CISP-PTE/红帽/ITIL/思科/华为/等中高级认证者优先；6. 具有良好的沟通能力和问题处理经验。",
      province: "山东省",
      city: "淄博市",
      district: "张店区",
      address: "淄博张店区齐赛大厦(齐赛三期)A座6",
      major: ["计算机", "网络空间安全"],
      neo4j: 5679,
      company: "维安（山东）数字技术有限公司",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "数据库工程师",
      salary: "15-30K",
      education: "大专",
      skill: [
        "PostgreSQL",
        "MongoDB",
        "Linux",
        "数据库",
        "flash",
        "Redis",
        "SSD",
        "Oracle",
        "MySQL",
        "OceanBase",
        "DM",
        "Unix",
        "DBA工作经验",
        "OCP",
        "OCM",
      ],
      info: "双休，定期体检，节假日加班费，法定节假日三薪，节日福利，餐补，晋升机制，学习分享，年终奖，意外险，股票期权，五险一金，员工旅游，团建聚餐，带薪年假",
      kind1: "互联网",
      kind2: "运维/技术支持",
      kind3: "DBA",
      description:
        "岗位职责：\n1、负责公司数据库服务项目及数据库产品(QFusion私有云平台、QData高性能数据库一体机、QBackup备份一体机等)项目的整体规划、技术方案制定、项目工作计划安排；\n2、协调项目干系人召开项目启动会，梳理项目背景、客户需求、项目目标、项目规划；\n3、协调公司资源，完成项目测试、实施、培训等各阶段工作，实现项目目标，为项目结果负责；\n4、项目信息记录，完善项目资料及公司产品后续故障bug跟踪反馈。\n5、客户售后数据库技术支持。\n6、公司产品数据库原型技术支持。\n7、数据库多元化技术预研。（Oracle/MySQL/PostgreSQL/Redis/MongoDB/MSSQL/DM/OceanBase/GaussDB等）\n任职资格：\n1、1-3年以上数据库从业经验；\n2、深入理解Oracle、MySQL、PostgreSQL、GaussDB、OceanBase等一种以上数据库体系架构，对构设计有较深入的研究和实践经验；\n3、精通Oracle、MySQL、PostgreSQL、GaussDB、OceanBase等一种以上数据库高可用技术，对其备份恢复、数据迁移、扩缩容等机制有实践经验；\n4、熟悉Oracle、MySQL、PostgreSQL、GaussDB、OceanBase等一种以上数据库优化方法论，对性能指标有深入研究，可独立对其进行优化工作；\n5、熟悉Oracle、MySQL、PostgreSQL、GaussDB、OceanBase等一种以上数据库故障诊断方法论，对其日志体系及错误信息有深入研究；\n6、了解主流Flash/SSD硬件技术，熟悉Linux/UNIX的日常操作；\n7、具备良好的沟通协作能力，有开拓进取的创新精神，能够承受较大的工作压力；\n8、同时具备多种数据库技能者优先；\n9、有乙方经验者优先。\n我们是一个数据库多元化的团队，团队中的每位同学均身兼多种数据库技能，如果你想挑战更多的数据库技能，欢迎你的加入！",
      province: "浙江省",
      city: "杭州市",
      district: "滨江区",
      address: "杭州滨江区智汇中心A座1103室",
      major: [],
      neo4j: 9621,
      company: "沃趣科技",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "前端实习生",
      salary: "50-100元/天",
      education: "硕士",
      skill: ["英文", "英语", "GIS", "vue", "vue.js"],
      info: "五险一金，带薪年假，餐补",
      kind1: "互联网",
      kind2: "运维/技术支持",
      kind3: "技术文档工程师",
      description:
        "职责描述:\n1、负责项目前端代码编写、研发等，进行前端代码的架构设计及优化工作;\n2、配合系统后端人员进行后台应用与前端页面的集成;\n3、负责撰写相关技术文档。\n任职要求:\n1、计算机、GIS等相关专业硕士学历；\n2、有vue.js项目开发经验，文档撰写能力佳着优先；\n3、有良好的中英文读写能力、英语口语流利者优先。",
      province: "重庆市",
      city: "市辖区",
      district: "沙坪坝区",
      address: "重庆沙坪坝区西永微电园沙坪坝区学城大道62-1研发楼一期B1栋902",
      major: ["计算机"],
      neo4j: 9070,
      company: "翌智航",
      logo: "https://img.bosszhipin.com/beijin/mcs/chatphoto/20200601/a7aaf773547b4b34ac4012225707f0e54d4dbf9cfb6155012d947907f184d504_s.jpg?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "软件工程师",
      salary: "14-18K·16薪",
      education: "大专",
      skill: ["ERP", "MES"],
      info: "定期体检，节日福利，全勤奖，五险一金",
      kind1: "互联网",
      kind2: "后端开发",
      kind3: "后端其他开发",
      description:
        "岗位职责：1：负责公司MES系统的管理与维护，与ERP接口的管理与维护2：配合MES系统供应商，进行系统二次开发3：监督MES系统操作，协调处理问题4：负责系统技术资料及各项资料的维护工作5：对公司软件的安装，维护，升级等进行管控6：领导交代的其他事项任职资格：1：大专及以上学历，计算机相关专业2：精通MES系统，金蝶K3云星空和ERP系统3：有制造业MES系统管理和金蝶K3云星空，ERP管理工作经验优先4：具有企业管理软件后台开发能力的优先5：爱岗敬业，态度认真，吃苦耐劳",
      province: "江苏省",
      city: "苏州市",
      district: "虎丘区",
      address: "苏州虎丘区江苏纳通能源技术有限公司C14",
      major: ["计算机"],
      neo4j: 1173,
      company: "江苏纳通能源技术有限公司",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "嵌入式软件工程师",
      salary: "15-25K",
      education: "大专",
      skill: [
        "C++",
        "PCB",
        "Uart",
        "数字",
        "芯片",
        "4G",
        "I2C",
        "IoT",
        "TCP/IP",
        "STM32",
        "嵌入式",
        "Linux",
        "模拟",
        "C",
        "udp",
        "HTTP",
        "NB-IoT",
        "ip",
        "USB",
        "WiFi",
        "SPI",
      ],
      info: "定期体检，餐补，零食下午茶，五险一金，通讯补贴",
      kind1: "电子",
      kind2: "电子/硬件开发",
      kind3: "嵌入式软件工程师",
      description:
        "岗位职责：1、能熟练进行WiFi芯片和4G/5G模块应用开发，并连接云平台。2、负责嵌入式STM32、 Linux等软件研发、协议研发，与公司IOT系统对接。3、使用C/C++语言进行嵌入式产品开发，参与嵌入式软件需求开发、设计、修改工作；3、负责产品芯片选型。4、负责产品的质量检测以及撰写相关评估报告。任职要求：1、本科以上学历，计算机、自动化或相关专业，有物联网、2年工作经验以上；2、熟悉ModBus-RTU、MQTT，Tcp/ip、Udp、Http可定制开发通信协议；3、精通STM32等ARM单片机，有较强的数字、模拟、电气电路设计能力。4、熟练使用PCB设计软件，可4层以上PCB板布线；5、精通TCP/IP、4G、NB-IoT、SPI、I2C、UART、USB等通信协议。6、熟悉产品硬件调试、测试、验证相关标准、熟悉基本仪器设备使用；7、有DTU设计开发工作经验优先。8、责任心强，善于沟通。备注：1、公司地址：广州市越秀区东华东路光东前街7号之一建东大厦7楼（即东华东路3路/215路车公交总站旁的楼上）。2、乘车路线：A、地铁1号线或6号线东山口站E或F出口，沿署前路、龟岗大马路方向直走8分钟即到。  B、公交3路/215路车东山总站（龟岗）旁。",
      province: "广东省",
      city: "广州市",
      district: "越秀区",
      address: "广州越秀区建东大厦光东前街7号",
      major: ["计算机", "自动化"],
      neo4j: 5336,
      company: "广东新邦智联科技有限公司",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "硬件工程师(人形机器人)",
      salary: "20-40K",
      education: "硕士",
      skill: [
        "CAN",
        "rs485",
        "IMU",
        "Pads",
        "PCB",
        "TCP/IP",
        "机器人行业",
        "rs232",
        "Modbus",
      ],
      info: "餐补，节日福利，定期体检，带薪年假，交通补助，五险一金",
      kind1: "电子",
      kind2: "电子/硬件开发",
      kind3: "硬件工程师",
      description:
        "岗位职责：\n1、负责人形机器人的控制系统硬件设计和开发；\n2、负责人形机器人控制系统硬件设计，调试，验证以及文档输出；\n3、负责人形机器人控制系统硬件缺陷整改与维护.\n岗位要求：\n1、硕士及以上学历，电子工程、计算机等相关专业性；\n2、5 年以上工作经验；\n3、精通模拟电路和数字电路设计、熟练掌握常用电子器件的电气特性；\n4、熟练掌握 Altium Designer 或 PADS 进行原理图和 PCB 设计；\n5、熟悉 RS232、RS485、CAN、TCP/IP 等通信方式；\n6、熟悉 EtherCAT 和 MODBUS 现场总线；\n7、了解 IMU、激光雷达等传感器，熟悉电池管理系统;\n8、有机器人控制系统硬件开发经验者优先.",
      province: "江苏省",
      city: "南京市",
      district: "江宁区",
      address: "南京江宁区南京埃斯顿智能系统工程有限公司吉印大道1888号",
      major: ["计算机", "电子工程"],
      neo4j: 11617,
      company: "埃斯顿自动化",
      logo: "https://img.bosszhipin.com/beijin/mcs/chatphoto/20180409/a2adbc2d6cbcb6b0700877411e6cb47ecfcd208495d565ef66e7dff9f98764da.jpg?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "汽车软件工程师",
      salary: "8-11K",
      education: "本科",
      skill: [
        "CAN",
        "LIN",
        "C++",
        "STM32开发",
        "嵌入式软件开发",
        "STM32",
        "计算机相关专业",
        "单片机",
        "C",
        "单片机设计经验",
      ],
      info: "补充医疗保险，年终奖，全勤奖，员工旅游，加班补助，住房補貼，带薪年假",
      kind1: "电子",
      kind2: "电子/硬件开发",
      kind3: "单片机",
      description:
        "1.有2年车载单片机开发的工作经验。\n2.熟悉stm32单片机的软件平台的搭建及开发经验。\n3.对汽车上的can,lin,iebus,非常熟悉，且有能力读取can,lin，iebus相关有用信息，并重新二次开发.\n4.能看懂电路图，熟悉电子技术原理，并有一定动手能力，分析及解决问题能力。\n盼望有志之士，加入我司一起创业",
      province: "广东省",
      city: "深圳市",
      district: "龙岗区",
      address: "深圳龙岗区龙信工业园A栋501",
      major: [],
      neo4j: 11093,
      company: "VSHAUto",
      logo: "https://img.bosszhipin.com/beijin/upload/com/logo/20201205/6f3c58eec273606d544fba71c33a0b7b3db66663b0f79e3ed2d55d1a402a3a00.jpg?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "高级DFT工程师",
      salary: "40-70K·15薪",
      education: "硕士",
      skill: [
        "Spyglass",
        "tessent",
        "VHDL",
        "Shell",
        "Python",
        "PT",
        "DFT",
        "ATPG",
        "shell",
        "ASIC",
        "MBIST",
        "Perl",
        "芯片设计",
        "Scan",
        "FCT",
        "TOP",
        "makefile",
        "STA",
        "RTL",
        "Verilog",
        "dc",
      ],
      info: "五险一金，生日福利，零食下午茶，带薪年假，补充医疗保险，员工旅游，股票期权，节日福利，年终奖，通讯补贴，团建聚餐，定期体检，意外险",
      kind1: "电子",
      kind2: "半导体/芯片",
      kind3: "DFT工程师",
      description:
        "岗位职责：\n1. 参与复杂芯片DFT/DFD/DFR的测试方案和架构定义；\n2. 实现Physical Block/tile级别的DFT功能，包括Scan、Boundary Scan、MBIST、MBISR, Scandump等功能；\n3. 产生DFT模式的时序约束，并配合PR和FCT团队完成时序收敛；\n4. 负责R2R，R2G的formal 约束和formal检查；\n5. 负责Block和top level各种测试模式，包括Scan、Boundary Scan、MBIST、MBISR, Scandump测试向量的产生和验证，最终交付ATE量产测试向量和HTOL/Burn-in测试向量；\n6. 评估和建立先进的DFT/DFD/DFR工具链和流程。\n任职要求：\n1. 本科5年以上或硕士3年以上DFT设计、验证和量产测试经验；\n2. 熟悉Scan/ATPG、MBIST、MBISR、Boundary Scan、Scandump等DFT技术；\n3. 熟悉Tessent工具链、SMS、DFT compiler、Spyglass DFT、Conformal、Formality、DC、PT等工具；\n4. 良好的数字ASIC设计基础，包括STA、验证和RTL编码；\n5. 精通verilog、system verilog，并能完成DFT定制模块的RTL编写；\n6. 良好的脚本语言知识，如TCL，Python，Perl，shell，Makefile；\n7. 良好的英语听说读写能力；\n8. 对日程安排和工作质量有强烈的承诺，良好的团队合作精神。",
      province: "上海市",
      city: "市辖区",
      district: "闵行区",
      address: "上海闵行区上海爱登堡科技产业园(孵化器)一楼",
      major: [],
      neo4j: 12082,
      company: "鸿钧微电子",
      logo: "https://img.bosszhipin.com/beijin/upload/com/workfeel/20220318/7bf6f160950405e97660ec9ccf9aae899bb434e6ef2bc2d77de3ad8647a682528dd5f7a931577828.jpg?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "资深DFT工程师（经理）",
      salary: "15-30K·14薪",
      education: "本科",
      skill: [
        "Shell",
        "Python",
        "电路设计",
        "芯片",
        "DFT",
        "shell",
        "PCIE",
        "Perl",
        "Linux",
        "FPGA开发",
        "Scan",
        "ddr",
        "FT",
        "PLL",
        "CP",
        "RTL",
        "TCL",
        "USB",
        "Verilog",
      ],
      info: "带薪年假，节日福利，绩效奖金，员工旅游，团建聚餐，定期体检，绩效奖金，年终奖，零食下午茶，五险一金",
      kind1: "电子",
      kind2: "半导体/芯片",
      kind3: "DFT工程师",
      description:
        "职责描述：\n1. 负责全芯片或者模板的DFT执行方案设计和实现，包括SCAN 插入，MBIST设计，ATPG测试向量生成，边界扫描，功能性测试向量生成等； 2. 负责IP的测试方案设计和实现，例如 DDR, PCIE, PLL, USB 等 3. 负责DFT相关的仿真验证，时序约束及收敛 4. 负责芯片的CP/FT 测试提供方案或执行支持\n任职要求：\n1. 熟悉Linux 开发环境及常用Linux 下文本编辑工具，熟悉Tcl/Perl 等脚本语言； 2. 熟练掌握主流的DFT工具，有多个芯片流片的成功经验； 3. 熟练掌握Verilog语言，并能够编写RTL代码与仿真 4. 熟练掌握脚本语言 (Tcl, Perl, Shell, Python等) 5. 熟悉综合，静态时序分析与形式验证 具备团队精神，自我管理能力强，能积极主动解决问题",
      province: "广东省",
      city: "珠海市",
      district: "香洲区",
      address: "珠海香洲区珠海中心大厦1604",
      major: [],
      neo4j: 12072,
      company: "珠海凌烟阁芯片科技",
      logo: "https://img.bosszhipin.com/beijin/upload/com/workfeel/20210610/fb30d220c01c92ffefcdc973795aed2e89ea23cfc8fc3554d2f60b3ced24853a.jpg?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "变流器软件高级工程师",
      salary: "15-25K·13薪",
      education: "硕士",
      skill: [
        "嵌入式软件开发",
        "仿真调试",
        "驱动开发",
        "单片机开发",
        "DSP",
        "C语言",
        "ti",
      ],
      info: "股票期权，员工旅游，团建聚餐，节日福利，有无线网，餐补，年终奖，意外险，零食下午茶，节假日加班费，带薪年假，绩效奖金，定期体检，五险一金，补充医疗保险，加班补助",
      kind1: "电子",
      kind2: "电子/硬件开发",
      kind3: "DSP开发",
      description:
        "岗位职责：\n1.负责储能变流器、风电变流器软件设计；\n2.产品开发相关文档的撰写；\n3.负责所开发的产品调试和测试；\n4.负责现场调试，与客户沟通等工作。\n职位要求：\n1.全日制硕士及以上学历，电气及自动化相关专业，专业基础扎实；\n2.2年以上电力电子变流器软件开发经验，具有独立开发变流器软件能力；\n3.熟悉TI DSP软件开发，熟悉光伏逆变器、风电变流器或储能变流器硬件结构和原理；\n4.工作积极主动，责任心强，具有较强的团队合作精神；\n5.认真、细致、负责的职业态度，善于沟通，适应阶段性的出差。",
      province: "北京市",
      city: "市辖区",
      district: "海淀区",
      address: "北京海淀区中关村东升科技园北领地D3",
      major: ["电子", "自动化"],
      neo4j: 10822,
      company: "雷动智创",
      logo: "https://img.bosszhipin.com/beijin/upload/com/logo/20220308/7b5b554d84f9729c5a77c2f8917f8832f742c59a94f1df17ad1ed3186def843a72fedaab9430e626.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "嵌入式工程师",
      salary: "2-3K",
      education: "本科",
      skill: [
        "ARM",
        "ADC",
        "C",
        "gcc",
        "IAR",
        "Uart",
        "SPI",
        "mcu",
        "I2C",
        "嵌入式",
      ],
      info: "员工旅游，全勤奖，工龄奖，加班补助，餐补，带薪年假，年终奖，交通补助，五险一金，节日福利，零食下午茶，生日福利，定期体检，团建聚餐",
      kind1: "电子",
      kind2: "电子/硬件开发",
      kind3: "嵌入式软件工程师",
      description:
        "岗位职责：1. 负责嵌入式产品软件平台设计开发、关键技术的研究；2. 负责产品与项目的软件总体方案设计，设计文档、测试文档等技术文件编写；3. 负责嵌入式软件的程序设计与代码编写，软件的调试、测试与维护；4. 负责与硬件工程师协作完成产品整机调试和测试；5. 负责配合内外部人员完成系统联调，针对调试出现的问题快速定位并解决；6. 负责已有产品的不断优化迭代工作。7. 因工作需要，公司所做的其他工作安排.任职要求：1. 有良好的软件开发习惯，能够撰写相关的技术文档；2. 能看懂基本的电路原理图；3. 熟悉ARM Cortex-M3/Cortex-M4硬件体系结构，具有STM32系列MCU开发经验者优先；4. 熟练使用C语言进行嵌入式软件开发，熟悉uCOS-II或uCOS-III，有相关开发经验者优先；5. 熟悉SourceInsight、MDK或IAR等编程及调试工具的使用，具有ARM GCC使用经验者优先；6. 精通外围设备/器件应用（UART/SPI/I2C/ADC等）及相关中英文datasheet阅读理解；7. 具有2年以上嵌入式软件开发工作经验；8. 良好的沟通表达能力；有理想和热情，紧跟行业技术发展趋势。9. 为人踏实、责任心强，有较强的钻研精神和团队合作意识。",
      province: "北京市",
      city: "市辖区",
      district: "海淀区",
      address: "北京海淀区民营科技创业园E座3层301室",
      major: [],
      neo4j: 5369,
      company: "北京国华世纪电子科技有限公司",
      logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "数字验证工程师",
      salary: "20-40K",
      education: "硕士",
      skill: [
        "芯片设计",
        "数字IC",
        "TCL",
        "UVM",
        "systemverilog",
        "Verilog",
        "芯片",
        "Perl",
      ],
      info: "定期体检，五险一金，节日福利，餐补，高温假",
      kind1: "电子",
      kind2: "半导体/芯片",
      kind3: "数字IC验证工程师",
      description:
        "岗位职责：\n1、理解模块及芯片设计规格，负责制定验证计划；\n2、根据芯片验证计划完成IP验证和系统级验证；\n3、构建验证环境及验证平台；\n4、负责生成和维护验证过程相关文档及报告；\n5、负责验证技术跟进及流程优化。\n任职要求：\n1、微电子/计算机/电子/自动化等相关专业，硕士研究生以上学历；\n2、熟悉芯片设计流程、数字IC验证流程，有流片经验者优先；\n3、精通Verilog、SystemVerilog、UVM验证方法学；\n4、熟悉Perl、Tcl等脚本语言；\n5、具有较强的分析解决问题能力和良好的团队合作精神;\n6、具有强烈自我驱动意识和奋斗精神。",
      province: "湖北省",
      city: "武汉市",
      district: "洪山区",
      address: "武汉洪山区709所电子楼17层",
      major: ["电子", "计算机", "微电子", "自动化"],
      neo4j: 12528,
      company: "凌久微",
      logo: "https://img.bosszhipin.com/beijin/upload/com/logo/20220210/7b5b554d84f9729c515ae3577217bfdff6e76dacf78d9d10e33c0014ec01b7f5d21c065e18dfdccb.png?x-oss-process=image/resize,w_100,limit_0",
    },
    {
      title: "定制电路设计工程师",
      salary: "15-25K·15薪",
      education: "硕士",
      skill: [
        "芯片设计",
        "PCB设计",
        "半导体技术",
        "Hspice",
        "Cadence",
        "电路设计",
        "ip",
        "数字",
        "Verilog",
      ],
      info: "节日福利，五险一金，加班补助，全勤奖，带薪年假，年终奖，定期体检，员工旅游",
      kind1: "电子",
      kind2: "半导体/芯片",
      kind3: "数字前端设计师",
      description:
        "岗位职责：\n1.负责模拟IP和存储IP的定制电路设计、仿真验证和测试工作；\n2.参与芯片需求分析、规格定义以及系统架构设计\n3.技术资料和文档的编写、维护、归档等工作。\n岗位要求：\n1.微电子/半导体/集成电路/电子/通信/自动化等相关专业，硕士及以上学历；\n2.掌握数字电路的基本结构以及半导体器件特性相关知识，\n3.熟练掌握Verilog/Spice等语言；\n4.熟练使用Virtusuo等电路设计工具以及Hspice/XA等仿真工具；\n5.具备良好的沟通能力、协作能力以及独立解决问题能力，工作主动性强。",
      province: "湖南省",
      city: "长沙市",
      district: "岳麓区",
      address: "长沙岳麓区中电软件园二期A5栋",
      major: ["电子", "自动化", "通信"],
      neo4j: 12723,
      company: "湖南融创微电子有...",
      logo: "https://img.bosszhipin.com/beijin/mcs/chatphoto/20200603/a4ed1e5779ce9d8497c5c90a9f2b7ca06ac8e5a891c5ed8cd445f42c353c9848_s.jpg?x-oss-process=image/resize,w_100,limit_0",
    },
  ],
});
