<template>
    <el-tabs v-model="activeName" class="demo-tabs" @tab-click="handleClick">
        <el-tab-pane label="互联网" name="first">
            <HotWorks />
        </el-tab-pane>
        <el-tab-pane label="AI/数据" name="second">
            <HotWorks2 />
        </el-tab-pane>
        <el-tab-pane label="电子" name="third">
            <HotWorks />
        </el-tab-pane>
        <el-tab-pane label="电气" name="fourth">
            <HotWorks />
        </el-tab-pane>
        <el-tab-pane label="通信" name="fifth">
            <HotWorks />
        </el-tab-pane>
    </el-tabs>
</template>

<script lang="ts" setup>
import { ref, computed } from "vue";
import type { TabsPaneContext } from "element-plus";
import HotWorks from "./HotWorks.vue";
import HotWorks2 from "./HotWorks2.vue";

// 假设您的原始数据存储在外部变量 data 中
const originalData = [
    [
        {
            title: "资深Java开发工程师",
            salary: "30-60K·16薪",
            education: "大专",
            skill: [
                "MyBatis",
                "NoSQL",
                "zookeeper",
                "Java",
                "Netty",
                "MongoDB",
                "SpringBoot",
                "数据结构",
                "Redis",
                "Dubbo",
                "SQL",
                "Kafka",
                "rocketmq",
                "IO",
                "RabbitMQ",
                "springcloud",
                "网络",
                "JVM",
            ],
            info: "交通补助，年终奖，五险一金，员工旅游，零食下午茶，餐补，带薪年假，节日福利，通讯补贴",
            kind1: "互联网",
            kind2: "后端开发",
            kind3: "Java",
            description:
                "职位要求：1.专科及以上学历，计算机相关专业，3-8年工作经验；2.Java基础扎实，精通多线程、并发、集合、网络、io等基础知识，熟悉JVM；3.熟练掌握各类算法、常用数据结构、设计模式和DDD领域建模；4.精通Apache DolphinScheduler等大数据分布式调度引擎；5.深入理解SpringBoot、SpringCloud、Dubbo、Netty、MyBatis、Sentinel、Nacos、Apollo等开源框架或产品（至少满足2项）的机制与代码；6.熟悉SQL、NoSQL、缓存、消息通信、队列、异步框架等技术；7.熟悉高性能、高并发系统设计方案，如分布式缓存、消息队列等；8.对典型的分布式场景有设计经验，掌握分布式键、分布式锁、分布式事务等关键技术，并能熟练应用；9.熟悉各类中间件（至少满足2项），如ZooKeeper、Redis、InfluxDB、MongoDB、RabbitMQ、Kafka、RocketMQ等；10.思路清晰，具有优秀的分析与沟通能力，编码规范。",
            province: "上海市",
            city: "市辖区",
            district: "杨浦区",
            address: "上海杨浦区互联宝地c2",
            major: ["计算机"],
            neo4j: 626,
            company: "上海识装信息科技有限公司",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "Android",
            salary: "6-12K",
            education: "本科",
            skill: [
                "Java",
                "ui",
                "app",
                "多线程",
                "Android",
                "android ndk",
                "Android Studio",
                "网络",
            ],
            info: "带薪年假，节日福利，餐补，年终奖，工龄奖，绩效奖金",
            kind1: "互联网",
            kind2: "前端/移动开发",
            kind3: "移动开发",
            description:
                "岗位职责：\n1、 从事安卓APP移动平台客户端软件的功能设计、开发和实现；\n2、 根据产品功能模块设计，编码实现各模块功能，并确保开发质量与进度；\n3、 对于产品的BUG进行问题的修正；\n4、 对移动端应用做出系统优化和数据优化；\n5、 产品的迭代和维护；\n岗位要求：\n1、熟练掌握Java, 熟悉面向对象思想，熟悉常用设计模式，编程习惯良好；\n2、熟练掌握安卓应用开发技术（包括UI、网络、存储、多线程等方面）、开发工具和测试工具；\n3、熟练掌握Android开发平台及框架原理，精通系统组件的使用，能进行自定义控件的封装；\n4、熟悉android屏幕适配，有APP性能优化的经验；\n5、有独立完整开发 App 经验优先，有个人上架 App 优先；\n6、良好的沟通及人际技巧，与团队成员高效协作；\n7.熟悉安卓各大市场APP上线流程",
            province: "安徽省",
            city: "合肥市",
            district: "瑶海区",
            address: "合肥合肥市瑶海区都市科技工业园C6栋101",
            major: [],
            neo4j: 8852,
            company: "统旭智慧科技",
            logo: "https://img.bosszhipin.com/beijin/upload/com/logo/20220926/7b5b554d84f9729c157fc655c4aecc0c8cf8e49fb37c6801ccd75b28d7f169b2a9c7a6bce39fbdca.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "小程序开发工程师",
            salary: "2-3K",
            education: "大专",
            skill: ["CSS", "Javascript", "HTML", "web", "小程序", "vuejs", "uni-app"],
            info: "全勤奖，五险一金，通讯补贴，带薪年假，生日福利，加班补助，年终奖，节日福利",
            kind1: "互联网",
            kind2: "前端/移动开发",
            kind3: "移动开发",
            description:
                "只要实习生，只要实习生，只要实习生！1、与后台工程师、设计师密切合作，参与前端产品的方案设计;2、参与公司项目设计、项目测试以及后期迭代的整个周期当中。任职要求:1、熟练掌握HTML、css、JavaScript;1到3年左右前端工作经验;2、熟悉Bootstr、Vuejs框架、uni-app前端应用框架;3、至少参与过一个完整Web项目开发。加分条件:1.熟悉uni-app框架;2.参与开发过微信小程序或者微信公众号的开发:3.有自己的作品展示。",
            province: "云南省",
            city: "曲靖市",
            district: "麒麟区",
            address: "曲靖麒麟区闽南建材城3区466号",
            major: [],
            neo4j: 6749,
            company: "上海酷柒网络技术有限公司",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "软件实施工程师",
            salary: "4-6K",
            education: "大专",
            skill: ["SaaS"],
            info: null,
            kind1: "互联网",
            kind2: "后端开发",
            kind3: "后端其他开发",
            description:
                "公司招聘：1、人事行政专员1名                    2、售后人员1名                    3、软件实施工程师2名薪资均4—6k，具体可以面谈需要相关工作经验至少半年企业介绍：四川仲医达医疗科技有限公司成立于2022年1月，是一家专业的SAAS服务供应商，股东背景为上市企业四川合纵药易购，公司强有力的上游供应链资源和阿里AI智能明星团队，将把基层医疗机构搭建为生态大平台。想要加入我们的小伙伴，快快联系吧。公司法定假日+五险一金+周末双休加分项有以下行业经验：医疗健康·计算机软件·计算机服务",
            province: "四川省",
            city: "成都市",
            district: "金牛区",
            address: "成都金牛区成都健康智谷7号楼15楼",
            major: ["计算机"],
            neo4j: 1045,
            company: "四川仲医达医疗科技有限公司",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "初级前端",
            salary: "2-3K",
            education: "大专",
            skill: ["GIT", "vue3", "Javascript", "web", "vue2", "HTML5", "vue"],
            info: "定期体检，通讯补贴，员工旅游，年假递增，餐补，补充医疗保险，节日福利，带薪年假，五险一金，加班补助，年终奖，股票期权",
            kind1: "互联网",
            kind2: "前端/移动开发",
            kind3: "前端开发工程师",
            description:
                "工作职责：1.根据项目要求，原型设计要求，完成系统前端开发工作；2.负责Web平台的前端技术框架研究和开发3.按照公司规范开发，保证交付代码质量，持续改进重构；4.配合产品、完成项目迭代，不断优化和提升用户体验5.深入分析和解决前端遇到的各种技术、性能、跨终端兼容问题6. 负责实现产品前端页面设计、开发，并整合前端与服务端代码任职要求：1.专科以上学历，只收24届应届生。最少时间 一年，固定1周至少5天可上岗，有项目经验请提供项目2.熟悉使用Javascript、Html5、CSS3、vue等前端开发技术栈。会Vue2/Vue3 ，熟悉git 的应届生优先考虑3.拥有良好的代码习惯，要求结构清晰，命名规范，逻辑性强，代码冗余率低4.具有快速学习和解决问题的能力。                                                            5.上班时间 朝九晚六，等福利，地铁口附近6.具备今日事今日毕的良好习惯",
            province: "福建省",
            city: "厦门市",
            district: "思明区",
            address: "厦门思明区观音山国际商务营运中心6号楼1",
            major: [],
            neo4j: 4244,
            company: "易视线（厦门）科技有限公司",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "网络安全工程师",
            salary: "8-12K·16薪",
            education: "大专",
            skill: ["华为", "ITIL"],
            info: "带薪年假，五险",
            kind1: "互联网",
            kind2: "运维/技术支持",
            kind3: "网络安全",
            description:
                "工作职责：1.完成客户网站、业务系统的等保安全评估工作；2.对客户各类信息化系统进行安全加固；3.对客户安全事件及时响应，清理后门，根据日志分析攻击途径；4.跟踪最近安全漏洞信息，进行安全技术研究，包括安全防范技术，黑客技术等；5.定期为客户交付安全类评估与漏扫报告；6.负责为客户及团队开展信息安全技术与管理领域相关培训；任职要求：1.计算机、网络空间安全或相关专业专科及以上学历；2.具有1年以上相关工作经历；3. 熟悉华为网络设备技术；4. 熟悉客户网络系统与防火墙、具备故障分析诊断、系统应急处理、网络优化及建议等二线技术支持能力。5.具有CISP-PTE/红帽/ITIL/思科/华为/等中高级认证者优先；6. 具有良好的沟通能力和问题处理经验。",
            province: "山东省",
            city: "淄博市",
            district: "张店区",
            address: "淄博张店区齐赛大厦(齐赛三期)A座6",
            major: ["计算机", "网络空间安全"],
            neo4j: 5679,
            company: "维安（山东）数字技术有限公司",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "数据库工程师",
            salary: "15-30K",
            education: "大专",
            skill: [
                "PostgreSQL",
                "MongoDB",
                "Linux",
                "数据库",
                "flash",
                "Redis",
                "SSD",
                "Oracle",
                "MySQL",
                "OceanBase",
                "DM",
                "Unix",
                "DBA工作经验",
                "OCP",
                "OCM",
            ],
            info: "双休，定期体检，节假日加班费，法定节假日三薪，节日福利，餐补，晋升机制，学习分享，年终奖，意外险，股票期权，五险一金，员工旅游，团建聚餐，带薪年假",
            kind1: "互联网",
            kind2: "运维/技术支持",
            kind3: "DBA",
            description:
                "岗位职责：\n1、负责公司数据库服务项目及数据库产品(QFusion私有云平台、QData高性能数据库一体机、QBackup备份一体机等)项目的整体规划、技术方案制定、项目工作计划安排；\n2、协调项目干系人召开项目启动会，梳理项目背景、客户需求、项目目标、项目规划；\n3、协调公司资源，完成项目测试、实施、培训等各阶段工作，实现项目目标，为项目结果负责；\n4、项目信息记录，完善项目资料及公司产品后续故障bug跟踪反馈。\n5、客户售后数据库技术支持。\n6、公司产品数据库原型技术支持。\n7、数据库多元化技术预研。（Oracle/MySQL/PostgreSQL/Redis/MongoDB/MSSQL/DM/OceanBase/GaussDB等）\n任职资格：\n1、1-3年以上数据库从业经验；\n2、深入理解Oracle、MySQL、PostgreSQL、GaussDB、OceanBase等一种以上数据库体系架构，对构设计有较深入的研究和实践经验；\n3、精通Oracle、MySQL、PostgreSQL、GaussDB、OceanBase等一种以上数据库高可用技术，对其备份恢复、数据迁移、扩缩容等机制有实践经验；\n4、熟悉Oracle、MySQL、PostgreSQL、GaussDB、OceanBase等一种以上数据库优化方法论，对性能指标有深入研究，可独立对其进行优化工作；\n5、熟悉Oracle、MySQL、PostgreSQL、GaussDB、OceanBase等一种以上数据库故障诊断方法论，对其日志体系及错误信息有深入研究；\n6、了解主流Flash/SSD硬件技术，熟悉Linux/UNIX的日常操作；\n7、具备良好的沟通协作能力，有开拓进取的创新精神，能够承受较大的工作压力；\n8、同时具备多种数据库技能者优先；\n9、有乙方经验者优先。\n我们是一个数据库多元化的团队，团队中的每位同学均身兼多种数据库技能，如果你想挑战更多的数据库技能，欢迎你的加入！",
            province: "浙江省",
            city: "杭州市",
            district: "滨江区",
            address: "杭州滨江区智汇中心A座1103室",
            major: [],
            neo4j: 9621,
            company: "沃趣科技",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "前端实习生",
            salary: "50-100元/天",
            education: "硕士",
            skill: ["英文", "英语", "GIS", "vue", "vue.js"],
            info: "五险一金，带薪年假，餐补",
            kind1: "互联网",
            kind2: "运维/技术支持",
            kind3: "技术文档工程师",
            description:
                "职责描述:\n1、负责项目前端代码编写、研发等，进行前端代码的架构设计及优化工作;\n2、配合系统后端人员进行后台应用与前端页面的集成;\n3、负责撰写相关技术文档。\n任职要求:\n1、计算机、GIS等相关专业硕士学历；\n2、有vue.js项目开发经验，文档撰写能力佳着优先；\n3、有良好的中英文读写能力、英语口语流利者优先。",
            province: "重庆市",
            city: "市辖区",
            district: "沙坪坝区",
            address: "重庆沙坪坝区西永微电园沙坪坝区学城大道62-1研发楼一期B1栋902",
            major: ["计算机"],
            neo4j: 9070,
            company: "翌智航",
            logo: "https://img.bosszhipin.com/beijin/mcs/chatphoto/20200601/a7aaf773547b4b34ac4012225707f0e54d4dbf9cfb6155012d947907f184d504_s.jpg?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "软件工程师",
            salary: "14-18K·16薪",
            education: "大专",
            skill: ["ERP", "MES"],
            info: "定期体检，节日福利，全勤奖，五险一金",
            kind1: "互联网",
            kind2: "后端开发",
            kind3: "后端其他开发",
            description:
                "岗位职责：1：负责公司MES系统的管理与维护，与ERP接口的管理与维护2：配合MES系统供应商，进行系统二次开发3：监督MES系统操作，协调处理问题4：负责系统技术资料及各项资料的维护工作5：对公司软件的安装，维护，升级等进行管控6：领导交代的其他事项任职资格：1：大专及以上学历，计算机相关专业2：精通MES系统，金蝶K3云星空和ERP系统3：有制造业MES系统管理和金蝶K3云星空，ERP管理工作经验优先4：具有企业管理软件后台开发能力的优先5：爱岗敬业，态度认真，吃苦耐劳",
            province: "江苏省",
            city: "苏州市",
            district: "虎丘区",
            address: "苏州虎丘区江苏纳通能源技术有限公司C14",
            major: ["计算机"],
            neo4j: 1173,
            company: "江苏纳通能源技术有限公司",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
    ],
    [
        {
            title: "数据研发",
            salary: "22-40K·16薪",
            education: "本科",
            skill: [
                "ElasticSearch",
                "clickhouse",
                "Java",
                "Spark",
                "Redis",
                "MySQL",
                "Hbase",
                "Scala",
                "Hadoop",
                "Kafka",
                "Clickhouse",
                "SQL",
                "Flink",
                "数据",
                "Hive",
            ],
            info: "带薪年假，免费班车，交通补助，五险一金，补充医疗保险，定期体检，年终奖，补充商业保险，通讯补贴",
            kind1: "AI/数据",
            kind2: "数据",
            kind3: "数据仓库",
            description:
                "岗位描述\n1、负责海量数据建模、分析、抽样以及评估平台的研发\n2、对每天百亿广告数据、媒体数据进行建模和分析处理，解决广告投放分析、广告推荐等问题。\n【任职要求】\n1.扎实的算法和数据结构功底，熟练掌握Java、Scala中至少一门编程语言；\n2.掌握海量数据处理技术，有使用Hadoop/Hive以及Map-Reduce计算模式，能熟练进行ETL处理TB级别数据，有Spark，Kafka，Elasticsearch，Hbase，Clickhouse等分析、存储海量数据的能力和经验。\n3.对数据仓库有深入了解，熟悉mysql、hive、redis等常用数据库。\n4.有Flink开发经验者优先。\n5.有数仓建设和数据分析经验者优先。",
            province: "北京市",
            city: "市辖区",
            district: "海淀区",
            address: "北京海淀区腾达大厦裙楼3层",
            major: [],
            neo4j: 11764,
            company: "易车",
            logo: "https://img.bosszhipin.com/beijin/mcs/banner/782c6c83d13e56c4b30e02d887de770acfcd208495d565ef66e7dff9f98764da.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "数据处理工程师",
            salary: "5-10K·13薪",
            education: "本科",
            skill: [
                "数据治理",
                "测绘",
                "遥感",
                "数据分析",
                "CSS",
                "Oracle",
                "MySQL",
                "SQL",
                "点云",
                "server",
                "数据库开发",
                "ArcGIS",
                "数据采集",
                "GIS",
            ],
            info: "全勤奖，住房补贴，年终奖，五险一金，包住，餐补，绩效奖金",
            kind1: "AI/数据",
            kind2: "人工智能",
            kind3: "数据挖掘",
            description:
                "岗位描述：\n1、负责遥感数据加工、处理、分析及解译等工作；\n2、负责项目数据组织、管理；\n3、严格按照项目技术方案熟练进行数据处理和质量控制；\n4、协助制定项目数据解决方案并提供解决办法；\n5、编写项目质量报告和总结文档。\n任职资格：\n1. 遥感、地理信息系统、测绘、地理等相关专业本科以上学历；\n2. 一年以上遥感影像数据处理方面工作经验；\n3. 熟练使用主流遥感影像解译分析处理软件；\n4. 熟练使用PIE-Map，ArcGIS、SuperMap等GIS软件；\n5. 熟悉遥感影像处理与解译分析流程，掌握遥感影像纠正、配准、融合、调色、镶嵌、增强、分类和信息提取等操作；\n6. 熟悉Oracle，SQL Server，MySQL等主流数据库和SQL基本语言；\n7. 责任心强、善于学习，注重自身发展与进步，具有良好的团队合作和沟通能力；\n8. 有一定行业项目经验者优先。",
            province: "北京市",
            city: "市辖区",
            district: "大兴区",
            address: "北京大兴区北京威特空间科技有限公司科苑路3号华日写字楼B座3层",
            major: [],
            neo4j: 10110,
            company: "威特空间",
            logo: "https://c-res.zhipin.com/jrs/fb9d87de5ed025fe0351abf96c5af692.jpg?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "大模型算法工程师（实习）",
            salary: "200-250元/天",
            education: "硕士",
            skill: ["Ai", "Kubernetes", "PyTorch"],
            info: "生日福利，节日福利，餐补，股票期权，零食下午茶，包吃，团建聚餐，员工旅游，交通补助，年终奖，五险一金",
            kind1: "AI/数据",
            kind2: "人工智能",
            kind3: "大模型算法",
            description:
                "能力要求\n- 计算机及计算机相关专业本科、硕士、博士在读\n- 极强的学习能力，能快速根据文档、在线资料，熟悉新系统，构建简单 AI 应用原型系统\n- 熟悉 PyTorch，有实际使用 PyTorch 进行模型训练、部署推理服务的经验\n- 熟悉 Kubernetes、Kubeflow 等主流的 AI 应用平台\n- Team player，积极乐观，开放包容，主动沟通、良好的协作能力\n岗位职责\n- 开发 Kubernetes 容器云平台上的 AI 微服务应用原型系统",
            province: "北京市",
            city: "市辖区",
            district: "海淀区",
            address: "北京海淀区宝盛广场c座一层",
            major: ["计算机"],
            neo4j: 9993,
            company: "算想未来",
            logo: "https://img.bosszhipin.com/beijin/upload/com/workfeel/20230718/7bf6f160950405e9767c17af998589da241dba9306a21b12a74bd2789296e4b90b8bac08793eaaf6.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "推荐算法",
            salary: "30-60K·15薪",
            education: "本科",
            skill: [
                "深度学习算法",
                "搜索算法",
                "机器学习算法",
                "算法设计",
                "广告算法",
            ],
            info: "定期体检，餐补，补充医疗保险，节日礼品，免费健身设施，就近租房补贴，家属自选保险，年终奖，交通补助，带薪年假，零食下午茶，意外险，股票期权，法定节假日三薪，餐饮及下午茶，团建聚餐，五险一金，家庭关爱假，弹性工作制，年度体检",
            kind1: "AI/数据",
            kind2: "人工智能",
            kind3: "推荐算法",
            description: "抖音游戏推荐，游戏业务场景推荐",
            province: "广东省",
            city: "深圳市",
            district: "南山区",
            address: "深圳南山区招商局广场-山海环幕全景写字楼111",
            major: ["游戏"],
            neo4j: 10447,
            company: "今日头条",
            logo: "https://img.bosszhipin.com/beijin/upload/com/workfeel/20231220/7bf6f160950405e993d5441fb36ed39b6e0ceee2dc588906180d77ff8d8c2e0a1cfd08ecf22f82f2.png.webp?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "SLAM算法工程师",
            salary: "12-24K",
            education: "博士",
            skill: ["C++", "C", "SLAM", "机器视觉", "matlab"],
            info: "五险一金，年终奖，补充医疗保险，定期体检",
            kind1: "AI/数据",
            kind2: "人工智能",
            kind3: "SLAM算法",
            description:
                "岗位职责:1、负责基于视觉+IMU融合的SLAM算法研发工作2、负责算法的实现和产品化岗位要求:1、有SLAM、SFM、定位算法经验，熟悉KF、ICP、图优化理论等2、熟悉目前主流的视觉VO/SLAM算法(如MSCKF、SVO、DSO、ORB-SLAM等)3、具有机器视觉、多传感器信息融合、惯导等组合导航专业知识4、熟练掌握C/C++/Matlab等常用编程语言5、具备良好的自学能力和沟通能力，具有较强的学习能力",
            province: "广东省",
            city: "深圳市",
            district: "宝安区",
            address: "深圳宝安区F518时尚创意园F16栋",
            major: [],
            neo4j: 795,
            company: "深圳增强现实技术有限公司",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "搜索算法工程师",
            salary: "30-50K·14薪",
            education: "本科",
            skill: [
                "数据挖掘",
                "机器学习",
                "Java",
                "Spark",
                "TensorFlow/PyTorch",
                "query",
                "nlp",
                "Python",
                "Kafka",
                "TensorFlow",
                "搜索/信息检索算法经验",
                "Hadoop/Hive/Spark",
                "CTR",
                "深度学习",
                "自然语言处理经验",
                "Hive",
            ],
            info: "12%公积金，股票期权，带薪年假，餐补，年终奖，节日福利，定期体检，五险一金，补充医疗保险",
            kind1: "AI/数据",
            kind2: "人工智能",
            kind3: "搜索算法",
            description:
                "职位职责：\n1. 负责小米平台十多款产品的搜索推荐业务，覆盖全球60多个国家20多种语言近3亿日活的流量，负责算法模型的建设优化，提升小米用户产品的体验；\n2、优化以大规模深度学习模型为核心的搜推系统，涵盖从Query/内容理解/召回/粗排/CTR精排模型/策略全链路模型的多种工作；\n3、探索最前沿的NLP技术，从基础的分词、NER，到应用上的Query分析、相关性、纠错等，全链路应用深度学习模型；\n4、挑战多语言多业务的复杂场景，面对全球化多语言的搜推业务和大搜多召回源类型的场景挑战，基于大模型进行深入创新探索；\n5、应用大规模深度学习技术，解决搜索中的推荐问题，让搜索更加个性化更加懂你；\n职位要求：\n1. 拥有计算机、机器学习、人工智能、数学等专业本科及以上学历，具备扎实的编程与算法基础;\n2. 熟悉主流的深度学习算法，熟悉TensorFlow等机器学习框架，熟练使用Java、Python等编程语言;\n3、熟悉常用的大数据处理平台工具，包括Spark/Hive/Kafka等，并有过处理分析数据经验；\n4、良好的业务理解能力，良好的沟通和协作能力；\n4、有过搜索/推荐/NLP/计算广告/数据挖掘方面经验优先。",
            province: "北京市",
            city: "市辖区",
            district: "昌平区",
            address: "北京昌平区小米智慧产业园区A栋",
            major: ["计算机", "人工智能", "数学"],
            neo4j: 10377,
            company: "小米",
            logo: "https://img.bosszhipin.com/beijin/mcs/banner/71f4ee09b9a2abfb675b5c705fc46c9dcfcd208495d565ef66e7dff9f98764da.jpg?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "搜索算法工程师（智谱AI-ChatGLM开源模型）",
            salary: "28-55K·15薪",
            education: "硕士",
            skill: [
                "搜索算法",
                "Linux",
                "LLaMA",
                "数据结构",
                "nlp",
                "Python",
                "检索",
                "计算机相关专业",
                "PyTorch",
                "Elasticsearch",
                "搜索/信息检索算法经验",
                "query search",
                "Ai",
                "LLM",
                "ChatGLM",
                "自然语言处理经验",
                "算法",
            ],
            info: "节日福利，年终奖，带薪年假，补充医疗保险，团建聚餐，生日福利，免费工装，餐补，定期体检，包吃，零食下午茶，五险一金，定期团建，股票期权",
            kind1: "AI/数据",
            kind2: "人工智能",
            kind3: "搜索算法",
            description:
                "职位描述：\n1. 参与智谱轻言的研发工作，构建新一代AI智能助手。研究和尝试新的搜索算法，提高搜索的效果和速度；\n2. 优化智谱轻言AI Agents效果，利用模型算法能力，提升用户体验；\n3. 优化重量级网页检索的搜索排序问题、搜索语义相关性、文档内容理解、质量、时效性等问题；\n4. 参与智谱轻言系统的开发和维护，保证系统的稳定性和可靠性；\n5. 协助产品和开发团队，为产品效果的优化和改进提供技术支持，保持行业领先水平。\n职位要求：\n1. 计算机、数学等相关专业，统招硕士及以上学历，3年及以上相关经验；\n2. 具备LLM的算法知识，熟悉常见的NLP算法和工具；\n3. 在深度学习、强化学习、NLP至少一个领域有较为深入的理解；\n4. 在网页搜索、搜索广告、智能客服、个人助手、文本挖掘等至少有一个业务场景有项目经验；\n5. 了解大模型基础知识及常见微调手段，熟悉ChatGLM、LLaMA等模型微调训练、优化方案者优先；\n6. 熟悉Pytorch、Huggingface等深度学习工具，熟悉Python编程语言，有Linux下的开发经验；\n7. 具备良好的数据结构和算法基础，扎实的编程功底；\n8. 逻辑思维能力强，具备良好的团队合作和沟通能力，能够积极参与项目组的讨论和决策。\n加分项：\n1. 熟悉智谱产品与相关大模型原理；\n2. 熟悉最新大模型相关算法；\n3. 熟悉图神经网络、多模态学习等搜索领域的先进技术；\n4. 有大模型相关产品落地开发经验；\n5. 发表过相关领域的高水平学术论文或拥有专利。",
            province: "北京市",
            city: "市辖区",
            district: "海淀区",
            address: "北京海淀区搜狐网络大厦9层",
            major: ["计算机", "数学"],
            neo4j: 10379,
            company: "智谱华章",
            logo: "https://img.bosszhipin.com/beijin/mcs/chatphoto/20210305/1755985002394c24760474e78c2e5484785f979a051c36d9a48b0186a0f0b391_s.jpg?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "技术负责人",
            salary: "35-45K",
            education: "本科",
            skill: [
                "Java",
                "Javascript",
                "Python",
                "Keras",
                "TensorFlow",
                "PyTorch",
                "GPT",
                "BERT",
                "计算机相关专业",
                "深度学习",
                "LLM",
                "Transformer",
            ],
            info: "定期体检，五险一金",
            kind1: "AI/数据",
            kind2: "人工智能",
            kind3: "自然语言处理算法",
            description:
                "岗位职责：\n1.和业务部门进行充分的需求交流，确定项目目标和技术方案。\n2.根据需求选择合适的LLM模型架构，完成模型的预训练/调优。\n3.制定模型持续训练和迭代方案，构建新数据反馈机制。\n4.跟踪项目进度，协调内部资源，如计算、存储等。\n5.建立知识库、沉淀方法论，能在工作中复用，并以培训等方式进行知识输出，赋能商业合作伙伴，或以反哺产品方式帮助产品优化迭代。\n任职要求：\n1.本科及以上学历，计算机科学、人工智能或相关专业优先。掌握至少一种编程语言，如Python、JavaScript、Java等。\n2.有LLM技术背景或经验，熟练掌握Tensorflow、PyTorch、Keras等其中一种深度学习框架，尤其是在大规模预训练语言模型如GPT方面的经验/研究；\n3.熟悉BERT,GPT-3,Transformer,RWKV等深度学习模型；了解不同的LLM模型架构优缺点，掌握LLM模型的训练、调优、嵌入（包括Embedding、Fine tuning等）技巧，确保模型达到应用需求，同时考虑模型落地的计算资源成本。\n5.了解大型语言模型的训练数据收集、预处理和标注方法，熟悉不同LLM任务的数据集和评价指标，能针对企业具体问题设计出有效的微调和评估方案。\n6.具备团队管理和项目管理经验，能高效协调技术人员按计划推进项目进程。\n7.良好的沟通技巧，能清晰解释技术方案，争取合作对象的支持。",
            province: "广东省",
            city: "广州市",
            district: "海珠区",
            address: "广州海珠区铭丰广场A座2802室",
            major: ["人工智能", "计算机科学"],
            neo4j: 9888,
            company: "武汉瑞泰企创",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
        {
            title: "算法工程师",
            salary: "40-70K·14薪",
            education: "硕士",
            skill: [
                "数据挖掘",
                "Linux",
                "机器学习",
                "Java",
                "C++",
                "Spark",
                "数据结构",
                "Python",
                "Scala",
                "Hadoop",
                "TensorFlow",
                "深度学习",
            ],
            info: "员工宿舍，带薪年假，定期体检，通讯补贴，年终奖，餐补，五险一金，员工补助，节日福利",
            kind1: "AI/数据",
            kind2: "人工智能",
            kind3: "其他AI",
            description:
                "1. 参与电商精准营销、用户行为挖掘、商品趋势洞察、搜索推荐等多个领域的算法研发工作，提升算法系统的性能和业务指标；2. 跟进机器学习、人工智能和其他技术在电商领域的创新和进展；3. 针对实际业务需求，分析问题，梳理数据，设计建模流程，推动实施完整的解决方案；4. 使用深度学习等技术开展图像、视频和NLP相关领域的探索研究。要求：1. 计算机、软件、自动化、数学等相关专业硕士及以上学历，3年以上相关工作经验；2. 熟悉常用的数据挖掘和机器学习算法，熟练掌握回归、分类、聚类等模型算法；3. 编程基础扎实，熟悉数据结构与算法，掌握C++/Python/Scala/Java等语言，熟悉Linux工作环境；4. 熟练使用Tensorflow/Spark/Hadoop等工具框架者优先；5. 出色的问题分析及解决能力，能自我驱动，持续面对挑战，积极主动、踏实勤奋。",
            province: "北京市",
            city: "市辖区",
            district: "通州区",
            address: "北京通州区京东集团总部B座",
            major: ["软件", "计算机", "数学", "自动化"],
            neo4j: 2455,
            company: "北京京东尚科信息技术有限公司",
            logo: "https://img.bosszhipin.com/beijin/icon/894ce6fa7e58d64d57e7f22d2f3a9d18afa7fcceaa24b8ea28f56f1bb14732c0.png?x-oss-process=image/resize,w_100,limit_0",
        },
    ],
];

const activeName = ref("first");

const handleClick = (tab: TabsPaneContext) => {
    activeName.value = tab.paneName as string;
};
</script>

<style scoped>
:deep(.el-tabs__header) {
    overflow: hidden;
    display: flex;
    justify-content: space-around;
}

.demo-tabs>.el-tabs__content {
    padding: 32px;
    color: #6b778c;
    font-size: 32px;
    font-weight: 600;
}
</style>
